version: '3.9'
services:
  web:
    build: /Users/noname/PycharmProjects/game_nerd
    command: gunicorn game_nerd.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./game_nerd/:/Users/noname/PycharmProjects/django/game_ners
    ports:
      - 8000:8000
    env_file:
      - ./game_nerd/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=noname
      - POSTGRES_DB=nerdy
volumes:
  postgres_data:
