# Generated by Django 4.0.2 on 2022-02-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
    ]
