# Generated by Django 4.0.2 on 2022-02-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitter",
            name="_id",
            field=models.CharField(max_length=300),
        ),
    ]
