# Generated by Django 4.0.2 on 2022-02-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_like_count_game_likes_delete_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="id_liker",
            field=models.BooleanField(default=0, verbose_name="liked"),
            preserve_default=False,
        ),
    ]
