# Generated by Django 4.0.2 on 2022-02-13 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="likes",
        ),
        migrations.AddField(
            model_name="game",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="game_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
