# Generated by Django 4.0.2 on 2022-02-13 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0004_remove_favorite_likes_game_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="like_count",
            field=models.BigIntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="game",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
