# Generated by Django 4.0.2 on 2022-02-14 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_rename_id_liker_game_is_liker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="is_liker",
            new_name="is_liked",
        ),
    ]
