# Generated by Django 4.0.2 on 2022-02-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_rename_is_liker_game_is_liked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Platforms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Twitter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=250)),
                ("twitter_id", models.IntegerField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="rating",
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="release_dates",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="summary",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.genres",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.platforms",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="tweets",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.twitter",
            ),
        ),
    ]
