# Generated by Django 4.0.2 on 2022-02-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_remove_game_is_liked_remove_game_like_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="game",
            name="platforms",
        ),
        migrations.RemoveField(
            model_name="game",
            name="tweets",
        ),
    ]
