# Generated by Django 4.0.2 on 2022-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_remove_game_genres_remove_game_platforms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genres",
            name="checksum",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genres",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genres",
            name="slug",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genres",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genres",
            name="url",
            field=models.URLField(default="www.test.com"),
            preserve_default=False,
        ),
    ]
