# Generated by Django 4.0.2 on 2022-02-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_alter_genres_created_at_alter_genres_updated_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Genres",
            new_name="Genre",
        ),
        migrations.RenameModel(
            old_name="Platforms",
            new_name="Platform",
        ),
    ]
