# Generated by Django 4.0.2 on 2022-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_rename_genres_genre_rename_platforms_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(
                null=True, related_name="genres", to="games.Genre"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(
                null=True, related_name="platforms", to="games.Platform"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="tweets",
            field=models.ManyToManyField(
                null=True, related_name="tweets", to="games.Twitter"
            ),
        ),
    ]
