# Generated by Django 4.0.2 on 2022-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0012_game_genres_game_platforms_game_tweets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_dates",
            field=models.CharField(blank=True, default=0, max_length=250),
            preserve_default=False,
        ),
    ]
