# Generated by Django 4.0.2 on 2022-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_alter_game_release_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
