# Generated by Django 4.0.2 on 2022-02-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_alter_game_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_dates",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
