# Generated by Django 4.0.2 on 2022-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_alter_game_release_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twitter",
            name="twitter_id",
        ),
        migrations.AddField(
            model_name="twitter",
            name="_id",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
