# Generated by Django 4.0.2 on 2022-02-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_remove_twitter_twitter_id_twitter__id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitter",
            name="_id",
            field=models.IntegerField(blank=True),
        ),
    ]
