# Generated by Django 4.0.2 on 2022-02-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0017_alter_twitter__id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitter",
            name="_id",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="twitter",
            name="created_at",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
