# Generated by Django 4.0.2 on 2022-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_alter_twitter__id_alter_twitter_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="summary",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
