# Generated by Django 4.0.2 on 2022-02-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='games.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='platforms', to='games.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tweets',
            field=models.ManyToManyField(related_name='tweets', to='games.Twitter'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
