# Generated by Django 4.0.2 on 2022-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_alter_game_genres_alter_game_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
