# Generated by Django 4.0.2 on 2022-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
